{{- $chart_name := .Chart.Name }}
{{- $chart_version := .Chart.Version | replace "+" "_" }}
{{- $release_name := .Release.Name }}

{{- range $job := .Values.jobs }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: "{{ $release_name }}-{{ $job.name }}"
spec:
  schedule: {{ $job.schedule | quote }}
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: {{ $job.restartPolicy }}
          containers:
          - name: {{ $job.name }}
            image: "{{ $job.image.repository }}:{{ $job.image.tag }}"
            imagePullPolicy: {{ $job.image.imagePullPolicy }}
            {{- with $job.env }}
            env:
{{ toYaml . | indent 12 }}
            {{- end }}
{{- end }}