apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: resource-limits
spec:
  replicas: 1
  resources:
    requests:
      cpu: 300m
      memory: 1Gi
    limits:
      cpu: 400m
      memory: 1Gi