name: crawler-scheduler CI workflow
on:
  push:
    branches:
      - 'master'
      - 'dev'
    paths:
      - 'crawler-scheduler/**/**.py'
      - 'crawler-scheduler/docker/Dockerfile'
      - 'rabbitmq/**/**.py'
      - '**.yaml'
  pull_request:
    branches:
      - 'master'
      - 'dev'
    paths:
      - 'crawler-scheduler/**/**.py'
      - 'crawler-scheduler/docker/Dockerfile'
      - 'rabbitmq/**/**.py'
      - '**.yaml'
env:
  # Define path for projects
  CRAWLER_BASE_PATH: crawler-scheduler
  CONTAINER_NAME: crawler-scheduler
jobs:
  crawler-build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./${{ env.CRAWLER_BASE_PATH }}/docker
          file: ./${{ env.CRAWLER_BASE_PATH }}/docker/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.CONTAINER_NAME }}:latest