name: CI for python
on:
  push:
    branches:
      - 'master'
      - 'dev'
    paths:
      - '**.py'
      - '**/**/Dockerfile'
  pull_request:
    branches:
      - 'master'
      - 'dev'
    paths:
      - '**.py'
      - '**/**/Dockerfile'
env:
  # Define path for projects
  CRAWLER_BASE_PATH: crawler
jobs:
  crawler-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9"]
    outputs:
      changed:  ${{ steps.labelStatus.outputs.changed }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Check out repository code to PR branch
        uses: actions/checkout@v3
        #with:
        #  ref: ${{ github.base_ref }}
      - name: Changed file filter
        uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            crawler:
              - 'crawler/**'
      # Check if crawler source code changed
      - name: check crawler source code
        if: steps.filter.outputs.crawler == 'true'
        run: |
          echo "crawler_changed_status=true >> $GITHUB_ENV
      - name: Install dependencies
        working-directory: ./${{ env.CRAWLER_BASE_PATH }}
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt          
      - name: Run unit tests
        working-directory: ./${{ env.CRAWLER_BASE_PATH }}
        run: |
          pip install pytest
          pip install pytest-cov
          pytest -v --junitxml="results.xml"
      - name: Label changed status
        id: labelStatus
        run: echo "::set-output name=changed::${{ env.crawler_changed_status }}"
  crawler-build:
    needs: crawler-test
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        if: needs.crawler-test.outputs.changed == 'true'
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        if: needs.crawler-test.outputs.changed == 'true'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up Docker Buildx
        if: needs.crawler-test.outputs.changed == 'true'
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        if: needs.crawler-test.outputs.changed == 'true'
        uses: docker/build-push-action@v2
        with:
          context: ./$CRAWLER_BASE_PATH/docker
          file: ./$CRAWLER_BASE_PATH/docker/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/$CRAWLER_BASE_PATH:latest